// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Zkmrops5PrmOCnxMfXSAR11WHqPWJJk',
    appId: '1:282557349670:web:6d199fb09dd08083f60be7',
    messagingSenderId: '282557349670',
    projectId: 'blogs-39931',
    authDomain: 'blogs-39931.firebaseapp.com',
    storageBucket: 'blogs-39931.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDeoXtuVaV78Ovp_Dy7-8N_uC2D5X13No',
    appId: '1:282557349670:android:ccf2f331ba7f10dbf60be7',
    messagingSenderId: '282557349670',
    projectId: 'blogs-39931',
    storageBucket: 'blogs-39931.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzdNe6OL0KI9xNJHPu3VGy8UahiyeFCso',
    appId: '1:282557349670:ios:8fe5c4fc5308cc24f60be7',
    messagingSenderId: '282557349670',
    projectId: 'blogs-39931',
    storageBucket: 'blogs-39931.appspot.com',
    iosBundleId: 'com.example.blogsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzdNe6OL0KI9xNJHPu3VGy8UahiyeFCso',
    appId: '1:282557349670:ios:8fe5c4fc5308cc24f60be7',
    messagingSenderId: '282557349670',
    projectId: 'blogs-39931',
    storageBucket: 'blogs-39931.appspot.com',
    iosBundleId: 'com.example.blogsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Zkmrops5PrmOCnxMfXSAR11WHqPWJJk',
    appId: '1:282557349670:web:73d2405e8e918c4cf60be7',
    messagingSenderId: '282557349670',
    projectId: 'blogs-39931',
    authDomain: 'blogs-39931.firebaseapp.com',
    storageBucket: 'blogs-39931.appspot.com',
  );
}
